apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sdb-controller.fullname" . }}
  labels:
    {{- include "sdb-controller.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdb-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
    - to: []
  ingress:
    - ports:
        - port: http
          protocol: TCP
